# Generated by Django 4.1.2 on 2022-10-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddados',
            name='casos_recuperados',
            field=models.CharField(default='\x16', max_length=100),
            preserve_default=False,
        ),
    ]
