# Generated by Django 4.1.2 on 2022-10-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_delete_coviddados'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casos_confirmados', models.CharField(max_length=100)),
                ('casos_recuperados', models.CharField(max_length=100)),
                ('mortes', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
