# Generated by Django 4.1.2 on 2022-10-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidDados',
        ),
    ]
