# Generated by Django 4.1.2 on 2022-10-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDadosVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_vacinacao_total_doses', models.CharField(max_length=100)),
                ('dados_vacinacao_primeira_dose', models.CharField(max_length=100)),
                ('dados_vacinacao_segunda_e_unica_dose', models.CharField(max_length=100)),
                ('dados_vacinacao_dose_reforco', models.CharField(max_length=100)),
                ('dados_vacinacao_data_atualizacao', models.DateField()),
            ],
        ),
    ]
